# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"

# Modern replacement for 'ls'
brew "exa"

# Command-line fuzzy finder written in Go
brew "fzf"

# User-friendly command-line shell for UNIX-like operating systems
brew "fish"

# GitHub command-line tool
brew "gh"

# Ambitious Vim-fork focused on extensibility and agility
brew "neovim", args: ["HEAD"]

# Search tool like grep and The Silver Searcher
brew "ripgrep"

# Cross-shell prompt for astronauts
brew "starship"

# Simplified and community-driven man pages
brew "tldr"

# Application launcher and productivity software
cask "alfred"

# Voice and text chat software
cask "discord"

# App to build and share containerized applications and microservices
cask "docker"

# Collaborative team software
cask "figma"

# Web browser
cask "google-chrome"

# GPU-based terminal emulator
cask "kitty"

# Knowledge base that works on top of a local folder of plain text Markdown files
cask "notion"

# Music streaming service
cask "spotify"
