# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 2

[character]      # The name of the module we are configuring is "character"
vicmd_symbol   = "[](bold blue)"
success_symbol = "[](bold green)"
