#! /bin/sh
source $DOTFILES/linux/log.sh

# Trap output to also write to log
LOG_FILE="$HOME/.sxhkd.log"
exec 3>&1 1>${LOG_FILE} 2>&1

log "kill running sxhkd instances"
# Terminate already running instances
killall -q sxhkd

# Wait until the processes have been shut down
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; log "waiting for previous sxhkd instance to be shutdown..."; done

log "xset cursor repeat rate"
xset r rate 150 50

picom -b --config $CONFIG/picom/picom.conf &

HOTKEYS=$(sh $DOTFILES/sxhkd/scripts/source_hotkeys.zsh)

log "start sxhkd"
sxhkd -c $DOTFILES/sxhkd/sxhkdrc $HOTKEYS

