#!/bin/bash

# Ask for the admin password upfront
echo "Please enter your password to install the necessary tools."
sudo -v

# Keep-alive: update existing `sudo` time stamp until script finishes
while true; do
  sudo -n true
  sleep 60
done 2>/dev/null &
sudo_pid=$!
trap 'kill $sudo_pid' EXIT

if ! xcode-select -p &>/dev/null; then
  echo "→ installing Xcode Command Line Tools..."
  xcode-select --install

  # Wait until the tools are installed
  until xcode-select -p &>/dev/null; do
    sleep 5
  done

  echo "✅ Xcode Command Line Tools installed"
else
  echo "✅ Xcode Command Line Tools already installed"
fi

echo "→ cloning dotfiles repository"
## check if the dotfiles directory already exists
if [ -d "$HOME/dotfiles" ]; then
  echo "The directory $HOME/dotfiles already exists. Please remove it before running this script."
  exit 1
else
  git clone https://github.com/jordykoppen/dotfiles $HOME/dotfiles
fi

echo "→ setting up necessary tools to continue installation..."

echo "→ installing Homebrew"
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo >> ~/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH="/opt/homebrew/bin:$PATH"

echo "→ installing fish"
brew install fish

echo "→ fish installed successfully. Adding to shells..."
sudo echo /opt/homebrew/bin/fish >> /etc/shells

echo "→ setting fish as the default shell..."
chsh -s /opt/homebrew/bin/fish

echo "→ done setting up base tools"

## source $HOME/dotfiles/setup_scripts/system_defaults

exec fish $HOME/dotfiles/install.fish
