#!/bin/bash

# Ask for the admin password upfront
echo "Please enter your password to install the necessary tools."
sudo -v

# Keep-alive: update existing `sudo` time stamp until script finishes
while true; do
  sudo -n true
  sleep 60
done 2>/dev/null &
sudo_pid=$!
trap 'kill $sudo_pid' EXIT

if ! xcode-select -p &>/dev/null; then
  echo "→ installing Xcode Command Line Tools..."
  xcode-select --install

  # Wait until the tools are installed
  until xcode-select -p &>/dev/null; do
    sleep 5
  done

  echo "✅ Xcode Command Line Tools installed"
else
  echo "✅ Xcode Command Line Tools already installed"
fi

echo "→ cloning dotfiles repository"
## check if the dotfiles directory already exists
if [ -d "$HOME/dotfiles" ]; then
  echo "The directory $HOME/dotfiles already exists. Please remove it before running this script."
  exit 1
else
  git clone https://github.com/jordykoppen/dotfiles $HOME/dotfiles
fi

echo "→ setting up necessary tools to continue installation..."

echo "→ installing Homebrew"
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo >> ~/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH="/opt/homebrew/bin:$PATH"

ln -sf $HOME/dotfiles/fish $HOME/.config/fish

echo "→ installing fish"
brew install fish > /dev/null

echo "→ fish installed successfully. Adding to shells..."
echo /opt/homebrew/bin/fish | sudo tee -a /etc/shells

echo "→ setting fish as the default shell..."
chsh -s /opt/homebrew/bin/fish

echo "→ done setting up base tools"

echo "→ symlinking dotfiles to home directory"
mkdir -p $HOME/.config
ln -sf $HOME/dotfiles/.gitconfig $HOME/.gitconfig
ln -sf $HOME/dotfiles/fish $HOME/.config/fish
ln -sf $HOME/dotfiles/atuin $HOME/.config/atuin
ln -sf $HOME/dotfiles/starship.toml $HOME/.config/starship.toml
ln -sf $HOME/dotfiles/nvim $HOME/.config/nvim
ln -sf $HOME/dotfiles/kitty $HOME/.config/kitty
ln -sf $HOME/dotfiles/gh $HOME/.config/gh

# Set up fish_greeting to run the setup script
fish -c "function fish_greeting; echo '🐟 Welcome to fish shell'; echo '⚡️ Setting up your environment as this is your first time...'; fish $HOME/dotfiles/setup.fish; end; funcsave fish_greeting"

echo ""
echo "✨ Installation complete! Please close this terminal and open a new one to continue the setup."
echo ""