#!/bin/bash

# Ask for the admin password upfront
echo "Please enter your password to install the necessary tools."
sudo -v

# Keep-alive: update existing `sudo` time stamp until script finishes
while true; do
  sudo -n true
  sleep 60
done 2>/dev/null &
sudo_pid=$!
trap 'kill $sudo_pid' EXIT

if ! xcode-select -p &>/dev/null; then
  echo "→ installing Xcode Command Line Tools..."
  xcode-select --install

  # Wait until the tools are installed
  until xcode-select -p &>/dev/null; do
    sleep 5
  done

  echo "✅ Xcode Command Line Tools installed"
else
  echo "✅ Xcode Command Line Tools already installed"
fi

echo "→ cloning dotfiles repository"
git clone https://github.com/jordykoppen/dotfiles $HOME/dotfiles

bash $HOME/dotfiles/setup_scripts/setup_base_tools
bash $HOME/dotfiles/setup_scripts/system_defaults
fish $HOME/dotfiles/install.fish
