#!/bin/bash

PASSPHRASE=(env LC_CTYPE=C tr -dc "a-zA-Z0-9-_\$\?" < /dev/urandom | head -c 100)
OUTPUT_LOCATION=($HOME/.ssh/id_ed25519)

# Generate key
ssh-keygen -t ed25519 -C "24296556+jordykoppen@users.noreply.github.com" -N $PASSPHRASE -f $OUTPUT_LOCATION

# Add key to keychain
ssh-add --apple-use-keychain $OUTPUT_LOCATION

# Add to config
echo " Host *
  UseKeychain yes
  AddKeysToAgent yes
  IdentityFile $OUTPUT_LOCATION" >> $HOME/.ssh/config 

# changing $DOTFILES git remote from https to ssh
git remote remove origin
git remote add origin git@github.com:jordykoppen/macos-dotfiles.git
