#!/usr/bin/env bash

# Installing and configuring fish shell.

# Symlink fish config dir from dotfiles.
ln -s "${HOME}/dotfiles/fish" "${HOME}/.config/fish"

echo "Change default shell to fish"
sudo bash -c 'echo /usr/local/bin/fish >> /etc/shells'
chsh -s /usr/local/bin/fish

echo "installing oh-my-fish"
curl -L https://get.oh-my.fish | fish
