#!/usr/bin/env bash

echo "installing yarn"
curl -o- -L https://yarnpkg.com/install.sh | bash

echo "installing node (via n-install)"
curl -L https://git.io/n-install | bash

echo "node --version: $(node --version)"
echo "npm --version: $(npm --version)"

echo "installing a few global npm packages"
npm install --global serve diff-so-fancy fkill-cli npm-quick-run semantic-release-cli
