#!/usr/bin/env bash

# installing neovim, vim-plug and installing all vim plugins.

echo "setting up vim-plug"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "installing vim pluggins"
nvim +silent +PlugInstall +qall
