#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "snazzy"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    # windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    statusline_unicode_symbols = true
    bootstrap_before = "myspacevim#before"
    # Enable vim compatible mode, avoid changing origin vim key bindings
    # vimcompatible = true
    # Put vimfiler on left
    sidebar_direction = 'left'
    autocomplete_method = 'coc'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'fzf'

[[layers]]
name= 'git'

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = "lang#typescript"

[[layers]]
name = 'lang#graphql'

[[layers]]
name = 'lang#rust'

[[custom_plugins]]
name = 'connorholyday/vim-snazzy'
merged = 0

[[layers]]
name = "colorscheme"
merged = 0

#[[custom_plugins]]
#name = "styled-components/vim-styled-components"
# [[custom_plugins]]
# name = "chrisbra/Colorizer"

[[custom_plugins]]
name = "peitalin/vim-jsx-typescript"

[[custom_plugins]]
name = "maxmellon/vim-jsx-pretty"

# [[custom_plugins]]
# name = "zxqfl/tabnine-vim"
