name: Build QMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - keyboards/qmk/**
      - .github/workflows/build-qmk-firmware.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Install jq
      run: apt update && apt install -y jq

    - name: Checkout userspace
      uses: actions/checkout@v4
      with:
        path: main
      
    - name: Checkout QMK firmware
      uses: actions/checkout@v4
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
        path: qmk_firmware
      
    - name: Copy user keyboard files into QMK
      run: cp -a main/keyboards/qmk/. qmk_firmware/keyboards/

    - name: Build firmware
      shell: bash
      run: |
        mkdir output
        cd qmk_firmware
        
        # Get list of changed files in the commit
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          # For manual triggers, build all keyboards
          changed_keyboards=$(jq -c '.[]' ../main/keyboards/qmk/keyboard_config.json)
        else
          # For push events, only build changed keyboards
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          changed_keyboards=$(jq -c '.[]' ../main/keyboards/qmk/keyboard_config.json | while read -r config; do
            keyboard=$(echo "$config" | jq -r '.keyboard')
            keyboard_path="keyboards/$keyboard"
            if echo "$changed_files" | grep -q "$keyboard_path"; then
              echo "$config"
            fi
          done)
        fi
        
        # Process each keyboard configuration
        echo "$changed_keyboards" | while IFS= read -r config; do
          if [ -n "$config" ]; then
            keyboard=$(echo "$config" | jq -r '.keyboard')
            keymap=$(echo "$config" | jq -r '.keymap')
            
            echo "Building firmware for $keyboard with keymap $keymap"
            qmk compile -kb "$keyboard" -km "$keymap"
            
            # Create output directory using the keyboard name
            output_name=$(echo "$keyboard" | tr '/' '_')
            mkdir ../output/"$output_name"
            cp -a .build/*.uf2 ../output/"$output_name"/
          fi
        done
  
    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-files
        path: output/
        if-no-files-found: error
