name: Build QMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - keyboards/qmk/**
      - .github/workflows/build-qmk-firmware.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Install jq
      run: apt update && apt install -y jq

    - name: Checkout userspace
      uses: actions/checkout@v4
      with:
        path: main
      
    - name: Checkout QMK firmware
      uses: actions/checkout@v4
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
        path: qmk_firmware
      
    - name: Copy user keyboard files into QMK
      run: cp -a main/keyboards/qmk/. qmk_firmware/keyboards/

    - name: Build firmware
      shell: bash
      run: |
        mkdir output
        cd qmk_firmware
        qmk compile -kb all -km jordy
  
    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-files
        path: output/
        if-no-files-found: error
