name: Build QMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - keyboards/qmk/

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
        - cornelius

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}

    - name: Copy user keyboard files into QMK
      run: |
        mkdir -p /opt/qmk_firmware/keyboards/cornelius
        cp -r users/${{ github.actor }}/keyboards/qmk/cornelius/* /opt/qmk_firmware/keyboards/cornelius/
      working-directory: .

    - uses: d3adb5/build-qmk-fw@v1
      with:
        keyboard: cornelius
        keymap: default
        output-dir: /keyboard-fimware
  
    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: built-images
        path: /keyboard-fimware
