name: Build QMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - keyboards/qmk/
      - .github/workflows/build-qmk-firmware.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
        - jornelius

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout userspace
      uses: actions/checkout@v4
      
    - name: Checkout QMK firmware
      uses: actions/checkout@v4
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
        path: qmk_firmware
      
    - name: Copy user keyboard files into QMK
      run: |
        ls -la $GITHUB_WORKSPACE/qmk_firmware
        ls -la $GITHUB_WORKSPACE/qmk_firmware/keyboards
        cp -a $GITHUB_WORKSPACE/keyboards/qmk/jornelius /opt/qmk_firmware/keyboards/jornelius

    - name: Build firmware
      run: |
        cd $GITHUB_WORKSPACE/qmk_firmware
        qmk compile -kb jornelius -km default
  
    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-files
        path: |
          $GITHUB_WORKSPACE/qmk_firmware/.build/*.uf2
          $GITHUB_WORKSPACE/qmk_firmware/.build/*.hex
