on:
  workflow_dispatch:
  pull_request:
    paths:
      - keyboards/zmk/**/*.*
  push:
    paths:
      - keyboards/zmk/**/*.*
jobs:
  build:
    uses: ./.github/workflows/build-user-config.yml
    with:
      zmk_config_path: keyboards/zmk
      config_path: config
      # archive_name: zmk_firmware
