name: Build QMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - keyboards/qmk/
      - .github/workflows/build-qmk-firmware.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
        - jornelius

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout userspace
      uses: actions/checkout@v4
      

    - name: Copy user keyboard files into QMK
      run: |
        ls -la /opt/qmk_firmware
        ls -la /opt/qmk_firmware/keyboards
        cp -a $GITHUB_WORKSPACE/keyboards/qmk/jornelius /opt/qmk_firmware/keyboards/jornelius

    - uses: d3adb5/build-qmk-fw@v1
      with:
        keyboard: jornelius
        keymap: default
        output-dir: /keyboard-fimware
  
    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: built-images
        path: /keyboard-fimware
