name: Build QMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - keyboards/qmk/

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
        - cornelius

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}

    - name: Copy user keyboard files into QMK
      run: |
        rm -rf /qmk_firmware/keyboards/foostan/cornelius
        mkdir -p /qmk_firmware/keyboards/foostan/cornelius
        cp -r users/${{ github.actor }}/keyboards/qmk/cornelius/* /qmk_firmware/keyboards/foostan/cornelius/
      working-directory: .

    - name: Build firmware
      run: qmk compile -kb "cornelius/rev2" -km default
      working-directory:  qmk_firmware
    
    - name: Archive firmware
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: cornelius-firmware
        path: |
          *.hex
          *.bin
          *.uf2
