name: Build QMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - keyboards/qmk/
      - .github/workflows/build-qmk-firmware.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
        - cornelius

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout userspace
      uses: actions/checkout@v4
      working-directory: .

    - name: Copy user keyboard files into QMK
      run: |
        ls -la /
        // copy from the userspace to the qmk firmware
        cp -a ${GITHUB_WORKSPACE}/dotfiles/keyboards/qmk/cornelius /opt/qmk_firmware/keyboards/cornelius
        ls -la /opt/qmk_firmware/keyboards/cornelius


    - uses: d3adb5/build-qmk-fw@v1
      with:
        keyboard: cornelius
        keymap: default
        output-dir: /keyboard-fimware
  
    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: built-images
        path: /keyboard-fimware
