on:
  workflow_dispatch:
  pull_request:
    paths:
      - keyboards/crkbd/**
  push:
    paths:
      - keyboards/crkbd/**
name: crkbd firmware build
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: keyboards/crkbd/build.yaml
      config_path: keyboards/crkbd/config/
