name: Build QMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - keyboards/qmk/
      - .github/workflows/build-qmk-firmware.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:

    - name: Checkout userspace
      uses: actions/checkout@v4
      with:
        path: main
      
    - name: Checkout QMK firmware
      uses: actions/checkout@v4
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
        path: qmk_firmware
      
    - name: Copy user keyboard files into QMK
      run: cp -a main/keyboards/qmk/jornelius qmk_firmware/keyboards/jornelius

    - name: Build firmware
      run: |
        mkdir output
        cd qmk_firmware
        qmk compile -kb jornelius -km default
        ls -la .build
        cp -a *.hex *.bin *.uf2 ../output/
  
    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-files
        path: |
          output/*.hex
          output/*.bin
          output/*.uf2
